Sanity check file location changes
nblockchain/geewallet pull request #236
Opened 2023-10-17 09:00 UTC by Mersho

2023-10-17 09:02 UTC, Mersho commented
I'm gonna push1by1...

2023-10-17 09:02 UTC, knocte commented on scripts/sanitycheck.fsx
> +    if solutions = null || solutions.Any() = false then
3 things:
* The way to check for null in F# is via the function isNull
* It is always better to write `not foo` than `foo = false`
* Anyway, in F# a null should almost never happen; would it happen here?

2023-10-17 09:03 UTC, knocte requested changes

2023-10-17 09:03 UTC, knocte commented on scripts/sanitycheck.fsx
> +        raise (FileNotFoundException())
@Mersho nit: by using <| then you avoid writing so many parentheses

2023-10-17 09:04 UTC, knocte commented
You should place the commit titled `scripts/sanitycheck: throw if sln doesn't exist` as the 1st in the PR, otherwise I don't see its effects in CI.

2023-10-17 09:06 UTC, knocte commented
The title "Sanity check file location changes" is very confusing because it doesn't really summarize the PR properly. I think the main issue that makes it very ambiguous is the absence of any verb in it.

2023-10-17 09:18 UTC, knocte commented on scripts/sanitycheck.fsx
> +        raise <| FileNotFoundException()
@Mersho this is the wrong way to throw this exception; it needs to receive the file name that was not found as an argument, to make it 200% more understandable to the person that receives this exception in their face please (always be thinking about the future developer that you're punishing, please; this practice is called "maintainability").

2023-10-17 09:21 UTC, Mersho commented on scripts/sanitycheck.fsx
> +        raise <| FileNotFoundException()
there's no way to throw exception based on whether each file exists or not, I can only throw an exception when no solution was found. I'm gonna create a better exception msg. Something like "No solution was found to do sanity check."

2023-10-17 09:24 UTC, knocte commented on scripts/sanitycheck.fsx
> +        raise <| FileNotFoundException()
You can throw that exception message with failwith, indeed. But I still want to see a FileNotFoundException thrown for when there is a solution file that doesn't exist. You can do that in each iteration.

2023-10-17 09:25 UTC, knocte commented
BTW please beware of your type `chenges` -> `changes`.

2023-10-17 09:26 UTC, knocte commented
> BTW please beware of your type chenges -> changes.

Typo: type->typo

2023-10-17 09:36 UTC, aarani commented on scripts/sanitycheck.fsx
> +        raise <| FileNotFoundException()
Haha, that failwith never happens. Iterations are done on files found by EnumerateFiles(). They all exist.

2023-10-17 10:30 UTC, knocte commented on scripts/sanitycheck.fsx
> +        System.IO.Path.Combine(FsxHelper.SourceDir.FullName, "gwallet.core-legacy.sln")
@Mersho please respect our coding guidelines: https://github.com/nblockchain/conventions/blob/master/docs/FSharpStyleGuide.md?plain=1#L88

2023-10-17 10:31 UTC, knocte commented on scripts/sanitycheck.fsx
> +    let checkFilesExist (fileNames: string list) =
@Mersho please respect our coding guidelines: https://github.com/nblockchain/conventions/blob/master/docs/FSharpStyleGuide.md?plain=1#L29

2023-10-17 10:31 UTC, knocte commented on scripts/sanitycheck.fsx
> +        raise <| FileNotFoundException("solution files were not found to do sanity check.")
@Mersho I told you that FileNotFoundException should only be used when supplying the file name that is not found

2023-10-17 10:32 UTC, knocte commented on scripts/sanitycheck.fsx
> +            sanityCheckNugetPackagesFromSolution (FileInfo <| solutionFileNames.[2])
@Mersho do not use FileInfo ctor here, it's too late, you should use it at the very beginning, otherwise you're not respecting our coding guidelines: https://github.com/nblockchain/conventions/blob/master/docs/WorkflowGuidelines.md?plain=1#L82

2023-10-17 10:32 UTC, knocte commented on scripts/sanitycheck.fsx
> +    if not (allFilesExist) then
@Mersho nit, no need for parentheses

2023-10-17 10:51 UTC, knocte commented
Ok, let's squash properly.

2023-10-17 11:16 UTC, knocte commented
I did NOT say squash commits into 1.

2023-10-18 04:12 UTC, knocte commented
> Bring back the sanity check

This PR title would make a future developer think that we had disabled or removed the sanity check and you brought it back. But this is **not** the case. The sanity check is/was there, you're just fixing one of its steps. Please fix the PR title.

2023-10-19 06:57 UTC, knocte commented
> Frontend.XF.*: sync & resolve packages conflict
>
> This commit upgrades packages in Frotend.XF.* projects
> to be in sync with versions used in Backend.
> 
> Sanity check was also complaining before this commit with
> the following error:

Also? The error you're quoting is exactly the same as the thing you're referring to before that paragraph. It is not two different problems, so I think you should remove the word `also`.

2023-10-19 06:58 UTC, knocte commented
> Fix sanitycheck.fsx script

The sanitycheck script has many steps. Not all of them were broken. Please re-read (paying attention to detail) what I said in https://github.com/nblockchain/geewallet/pull/236#issuecomment-1767607747

2023-10-19 07:29 UTC, knocte commented
> scripts/sanitycheck.fsx: fix dotnet legacy

**dotnet legacy**??? That sounds so weird and looks like a contradiction, given that in .NET4.x (legacy), the command `dotnet` doesn't exist. Please change the above to read `.NET legacy` to avoid any possible confusions.

2023-10-20 11:25 UTC, knocte commented
> Readjustment sanitycheck.fsx script

Why did you remove the word "fix" from the title? I did not have a complain about that word. Please read again my previous complaint @Mersho .

2023-10-20 19:24 UTC, merged